configs:
  linear_baseline:
    model: linear_baseline
    lr: 0.001
    optimizer: adam

  efficientnet_b0:
    model: efficientnet
    variant: 0
    weights: EfficientNet_B0_Weights.DEFAULT
    lr: 0.001
    optimizer: adam
    layers_to_unfreeze: 0
    dropout: 0.4
  
  efficientnet_b1:
    model: efficientnet
    variant: 1
    weights: EfficientNet_B1_Weights.DEFAULT
    lr: 0.001
    optimizer: adam
    layers_to_unfreeze: 0
    dropout: 0.4

  efficientnet_b3:
    model: efficientnet
    variant: 3
    weights: EfficientNet_B1_Weights.DEFAULT
    lr: 0.001
    optimizer: adam
    layers_to_unfreeze: 0
    dropout: 0.4
  

  transforms:

training:
  batch_size: 32
  epochs: 50
  seed: 42
  loss_weights: [1.0, 3.0] # up-weight protein
  unfreeze_patience: 5
  lr_backbone = 1e-5

