configs:
  linear_baseline:
    model: linear
    lr: 0.001
    optimizer: adam

  efficientnet_b0:
    model: efficientnet
    variant: b0
    weights: EfficientNet_B0_Weights.DEFAULT
    lr: 0.0001
    optimizer: adam
    layers_to_unfreeze: 0
    unfreeze_epoch: 5      # unfreeze after 5 epochs for fine-tuning
    dropout: 0.4
  
  efficientnet_b1:
    model: efficientnet
    variant: b1
    weights: EfficientNet_B1_Weights.DEFAULT
    lr: 0.0001
    optimizer: adam
    layers_to_unfreeze: 0
    unfreeze_epoch: 5      # unfreeze after 5 epochs for fine-tuning
    dropout: 0.4
  
  resnet:
    model: resnet100

  transforms:
    